### ISSUE TITLE
Spark health check failed

### ISSUE THREAD

**Issue by wei-orchid** [nchammas/flintrock#126]
I always get "Spark health check failed", and I have no chance to type n when console prints "Do you want to terminate the 2 instances created by this operation? [Y/n]"

* Flintrock version: 0.4.0
* Python version: Python 3.4.3
* OS: Amazon Linux

command: flintrock --config config.yaml launch test_cluster

config.yaml:
```
services:
  spark:
    version: 1.6.0
  hdfs:
    version: 2.7.1

provider: ec2

providers:
  ec2:
    key-name: gridx-oregon-infra
    identity-file: /home/ec2-user/gridx-oregon-infra.pem
    instance-type: m3.2xlarge
    region: us-west-2
    availability-zone: us-west-2b
    ami: ami-7172b611   # Amazon Linux, us-east-1
    user: ec2-user
    spot-price: 0.2
    vpc-id: vpc-f7740f93
    subnet-id: subnet-a77b13c3
    tenancy: default  # default | dedicated
    ebs-optimized: no  # yes | no
    instance-initiated-shutdown-behavior: terminate  # terminate | stop

launch:
  num-slaves: 1
```

log:
```
Requesting 2 spot instances at a max price of $0.2...
0 of 2 instances granted. Waiting...
All 2 instances granted.
[54.200.151.5] SSH online.
[54.200.151.5] Configuring ephemeral storage...
[54.149.49.130] SSH online.
[54.149.49.130] Configuring ephemeral storage...
[54.200.151.5] Installing Spark...
[54.149.49.130] Installing Spark...
[10.0.0.183] Configuring Spark master...
n

Spark health check failed.
There was a problem with the launch. Cleaning up...
Do you want to terminate the 2 instances created by this operation? [Y/n]: Traceback (most recent call last):
  File "urllib/request.py", line 1240, in do_open
  File "http/client.py", line 1083, in request
  File "http/client.py", line 1128, in _send_request
  File "http/client.py", line 1079, in endheaders
  File "http/client.py", line 911, in _send_output
  File "http/client.py", line 854, in send
  File "http/client.py", line 826, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 698, in create_connection
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "flintrock/flintrock.py", line 871, in main
  File "site-packages/click/core.py", line 716, in __call__
  File "site-packages/click/core.py", line 696, in main
  File "site-packages/click/core.py", line 1060, in invoke
  File "site-packages/click/core.py", line 889, in invoke
  File "site-packages/click/core.py", line 534, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "flintrock/flintrock.py", line 322, in launch
  File "flintrock/ec2.py", line 46, in wrapper
  File "flintrock/ec2.py", line 629, in launch
  File "flintrock/core.py", line 431, in provision_cluster
  File "flintrock/services.py", line 333, in health_check
  File "urllib/request.py", line 162, in urlopen
  File "urllib/request.py", line 465, in open
  File "urllib/request.py", line 483, in _open
  File "urllib/request.py", line 443, in _call_chain
  File "urllib/request.py", line 1268, in http_open
  File "urllib/request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
standalone returned -1
```

**Comment by nchammas** [comment]
> ```
[10.0.0.183] Configuring Spark master...
```

Looks like you're trying to create a cluster inside a private VPC. Is that correct?

**Comment by wei-orchid** [comment]
the vpc has a single public subnet, i think it is not a private vpc

**Comment by nchammas** [comment]
The `10.0.0.183` address suggests otherwise, though I am confused by the fact that earlier in your output the addresses are all public (`54...`). My guess is something must be off about the VPC configuration, or one of the related components like the subnet, routing table, and so forth.

Do you see the same behavior if you run Flintrock off of `master`? Instructions to install this version are [here](https://github.com/nchammas/flintrock#development-version).

**Comment by wei-orchid** [comment]
Thanks for your quick reply! I used flintrock standalone package, I will try the other versions

**Comment by nchammas** [comment]
@wei-orchid - Do you still see this in Flintrock 0.5.0?

**Comment by lipingzh** [comment]
@nchammas  I also used Flintrock 0.5.0, still got no luck.

root@ip-10-0-0-198:~# flintrock --config config.yaml launch test_1
Requesting 3 spot instances at a max price of $0.2...
0 of 3 instances granted. Waiting...
0 of 3 instances granted. Waiting...
All 3 instances granted.
[54.149.213.34] SSH online.
[54.149.213.34] Configuring ephemeral storage...
[54.186.92.160] SSH online.
[54.186.92.160] Configuring ephemeral storage...
[54.149.213.34] Installing Spark...
[54.218.35.231] SSH online.
[54.218.35.231] Configuring ephemeral storage...
[54.186.92.160] Installing Spark...
[54.218.35.231] Installing Spark...
There was a problem with the launch. Cleaning up...
Do you want to terminate the 3 instances created by this operation? [Y/n]: Y
Terminating instances...
[ec2-54-149-213-34.us-west-2.compute.amazonaws.com] Could not connect via SSH.

**Comment by nchammas** [comment]
@lipingzh - That looks like a slightly different issue.

```
[ec2-54-149-213-34.us-west-2.compute.amazonaws.com] Could not connect via SSH.
```

That's weird since Flintrock connects via IP, not DNS name. Do you see this consistently?

**Comment by lipingzh** [comment]
@nchammas Thanks for your response. Yes, it happened consistently.  

 I also used private VPC without DNS to launch it before, but it was failed to  launch and ask me to use DNS, that's why I use current new vpc with DNS.

**Comment by nchammas** [comment]
@lipingzh

> but it was failed to launch and asked me to use DNS

Just curious: Can you paste the error you got?

Also, Flintrock does not currently support launching clusters into private VPCs (see #14). Have you tried working with a completely public VPC? It looks like that's what you're working with, but I'm not sure if there is something special about it.

**Comment by nchammas** [comment]
Any updates from @wei-orchid or @lipingzh on what you're seeing with the latest version of Flintrock with completely public VPCs?

As things stand, I don't have enough information to act on this issue.

**Comment by nchammas** [comment]
Closing this due to lack of information. Feel free to reopen if you have more specific and actionable information about what's going wrong.

**Comment by fazish** [comment]
Hello, dear @nchammas 
I have got the same error
![image](https://user-images.githubusercontent.com/38839459/58759247-7a2f1400-8559-11e9-9fa2-299249549df8.png)

After pressing y 
![image](https://user-images.githubusercontent.com/38839459/58759254-93d05b80-8559-11e9-8997-ba09eda4428d.png)
 
Spark version is 2.3.3
and the spark datasorce is :
https://www-us.apache.org/dist/spark/spark-{v}/spark-{v}-bin-hadoop2.7.tgz

**Comment by nchammas** [comment]
@fazish - Please open a new issue and provide some additional detail like your full Flintrock config, the version of Flintrock you're using, etc.
