### ISSUE TITLE
Dangerous behaviour when num-slaves=0

### ISSUE THREAD

**Issue by sylvinus** [nchammas/flintrock#140]
Hi!

I wanted to launch just one master to do some tests, so I set `num-slaves: 0`.

That was a mistake. *All* my EC2 instances got renamed to `[cluster_name]-slave` and tagged as `flintrock-role=slave`.

In addition to that, there is an error:
```
# flintrock launch fr
Requesting 1 spot instances at a max price of $0.3...
0 of 1 instances granted. Waiting...
0 of 1 instances granted. Waiting...
All 1 instances granted.
There was a problem with the launch. Cleaning up...
Do you want to terminate the 1 instances created by this operation? [Y/n]: n
Traceback (most recent call last):
  File "/usr/local/bin/flintrock", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flintrock/flintrock.py", line 885, in main
    cli(obj={})
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/flintrock.py", line 336, in launch
    instance_initiated_shutdown_behavior=ec2_instance_initiated_shutdown_behavior)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 46, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 668, in launch
    cluster.wait_for_state('running')
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 115, in wait_for_state
    (self.master_instance, self.slave_instances) = _get_cluster_master_slaves(instances)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 804, in _get_cluster_master_slaves
    raise Exception("No master found.")
Exception: No master found.
root@196a82c228f0:/cosr/ops# flintrock login fr
Traceback (most recent call last):
  File "/usr/local/bin/flintrock", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flintrock/flintrock.py", line 885, in main
    cli(obj={})
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/flintrock.py", line 496, in login
    vpc_id=ec2_vpc_id)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 720, in get_cluster
    vpc_id=vpc_id)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 765, in get_clusters
    for cluster_name in found_cluster_names]
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 765, in <listcomp>
    for cluster_name in found_cluster_names]
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 816, in _compose_cluster
    (master_instance, slave_instances) = _get_cluster_master_slaves(instances)
  File "/usr/local/lib/python3.4/dist-packages/flintrock/ec2.py", line 804, in _get_cluster_master_slaves
    raise Exception("No master found.")
Exception: No master found.
```

The most dangerous issue seems to be here:
https://github.com/nchammas/flintrock/blob/6b84d2885348205e00c45a4d67b1a23dbbd4cb92/flintrock/ec2.py#L654

I think that `.filter(InstanceIds=[])` doesn't filter anything, so all the instances get tagged.

Thanks!

**Comment by nchammas** [comment]
This is addressed by [an open PR](https://github.com/nchammas/flintrock/pull/115/files#diff-68ae40482e972a52a1e610945245d2a5R179), which forbids launching a cluster with 0 slaves. Sorry it's been taking me a while to get that done.

The plan is to re-allow 0-slave cluster launches at some later point, and do so carefully to avoid problems like this.

**Comment by nchammas** [comment]
> I think that .filter(InstanceIds=[]) doesn't filter anything, so all the instances get tagged.

For the record, that's correct. The upstream issue is here: https://github.com/boto/boto3/issues/479
