### ISSUE TITLE
Diagnosing connection issues

### ISSUE THREAD

**Issue by mrocklin** [nchammas/flintrock#170]
Hi, I'm running from Ubuntu, conda-installed Python and pip installed flintrock/paramiko and am running into the following error:

```
mrocklin@carbon:~$ flintrock launch test-cluster
^[[5;5~Launching 2 instances...
Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1884, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/packet.py", line 485, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1740, in run
    self._check_banner()
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1888, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1884, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/packet.py", line 487, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1740, in run
    self._check_banner()
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1888, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1884, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/packet.py", line 485, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/bin/flintrock", line 11, in <module>
    load_entry_point('Flintrock==0.8.0.dev0', 'console_scripts', 'flintrock')()
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/flintrock.py", line 1068, in main
    cli(obj={})
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/flintrock.py", line 352, in launch
    user_data=ec2_user_data)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/ec2.py", line 48, in wrapper
    res = func(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/ec2.py", line 937, in launch
    identity_file=identity_file)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/core.py", line 613, in provision_cluster
    _run_asynchronously(partial_func=partial_func, hosts=hosts)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/core.py", line 473, in _run_asynchronously
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/home/mrocklin/Software/anaconda/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/home/mrocklin/Software/anaconda/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/mrocklin/Software/anaconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/core.py", line 673, in provision_node
    wait=True)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/flintrock/ssh.py", line 73, in get_ssh_client
    timeout=3)
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/client.py", line 338, in connect
    t.start_client()
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 493, in start_client
    raise e
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1740, in run
    self._check_banner()
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/paramiko/transport.py", line 1888, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
```

This is very likely not flintrock's fault, but I've done enough unsuccessful Googling that I decided it was worth querying here to see if others have run into this same problem.  This issue occurs on my system both with flintrock's latest release, and with git-master.

**Comment by nchammas** [comment]
Various people (myself included) have hit this error under various circumstances, and unfortunately the cause seems to be different every time. 

https://github.com/nchammas/flintrock/search?q=Error+reading+SSH+protocol+banner&type=Issues&utf8=✓

What AMI and login username are you using?

Are you able to launch an instance and SSH into it outside of Flintrock?

**Comment by mrocklin** [comment]
I'm using the default config ami and user.  Launching a cluster now to test ssh access.

    ami: ami-b73b63a0   # Amazon Linux, us-east-1
    user: ec2-user

**Comment by mrocklin** [comment]
Attempts to SSH fail:

```
mrocklin@local:~$ ssh -i .ssh/my-key.pem ec2-user@remote-ip
Permission denied (publickey).
```

**Comment by nchammas** [comment]
Looks like you're using the wrong SSH private key. Is it the one associated with the key pair you set in your config?

**Comment by mrocklin** [comment]
OK, I've made a new AWS secret, and a new keypair and am using those now and things seem to work fine.  

I was getting this for a while:

```
mrocklin@carbon:~$ flintrock launch test-cluster
Flintrock could not find a default VPC in us-east-1. Please explicitly specify a VPC to work with in that region. Flintrock does not support managing EC2 clusters outside a VPC.
```

But that probably has more to do with my settings than with `flintrock`.  I resolved this by switching to a different region and using an appropriate AMI.

**Comment by nchammas** [comment]
Yeah, you've probably been using EC2 in us-east-1 since before 2015, which is why you don't have a default VPC there. You can either create a VPC and mention it explicitly in your config, or switch as you did to a region that you first used after roughly spring 2015, in which case you'd have a default VPC setup for you by Amazon. 

I'll create a separate issue to give some hints to the user when Flintrock encounters the SSH banner error.
