### ISSUE TITLE
Security Group Limit

### ISSUE THREAD

**Issue by PiercingDan** [nchammas/flintrock#173]
* Flintrock version: 0.6.0
* Python version: 3.5.1 :: Anaconda custom (64-bit)
* OS: Ubuntu 16.04

Minor issue occurs when trying to use flintrock on the same AWS account but from different IP address, flintrock will attempt to modify the existing security groups to add the new rules corresponding to the new IP address, but this will fail if the number of rules on Flintrock base group or Flintrock cluster group exceeds the limit (50). I workaround this by deleting the old security groups.

```
[LocalComputer]$ flintrock launch test-cluster

Traceback (most recent call last):
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/flintrock/ec2.py", line 559, in get_or_create_flintrock_security_groups
    CidrIp=rule.cidr_ip)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (RulesPerSecurityGroupLimitExceeded) when calling the AuthorizeSecurityGroupIngress operation: The maximum number of rules per security group has been reached.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dluo/anaconda3/bin/flintrock", line 11, in <module>
    sys.exit(main())
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/flintrock/flintrock.py", line 1034, in main
    cli(obj={})
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/flintrock/flintrock.py", line 339, in launch
    instance_initiated_shutdown_behavior=ec2_instance_initiated_shutdown_behavior)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/flintrock/ec2.py", line 46, in wrapper
    res = func(*args, **kwargs)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/flintrock/ec2.py", line 832, in launch
    region=region)
  File "/home/dluo/anaconda3/lib/python3.5/site-packages/flintrock/ec2.py", line 562, in get_or_create_flintrock_security_groups
    raise Exception("Error adding rule: {r}".format(r=rule))
Exception: Error adding rule: SecurityGroupRule(ip_protocol='tcp', from_port=6066, to_port=6066, src_group=None, cidr_ip='70.50.132.240/32')
```

**Comment by nchammas** [comment]
Thanks for reporting this @PiercingDan. I've hit this issue as well many times, and my current workaround is the same as yours.

I think the best fix for this is to turn the base security group `flintrock` into a dummy group with no rules that's used just to identify Flintrock clusters, and move all the access rules to the individual cluster security groups (e.g. `flintrock-mycluster`) which get created and destroyed with the clusters themselves. That should avoid us hitting any limits.
