### ISSUE TITLE
describe --master-hostname-only logging error

### ISSUE THREAD

**Issue by tyg03485** [nchammas/flintrock#263]
I'm trying to run flintrock.py describe functions with "--master-hostname-only" option, but they return error with logging.

here is the error.
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/flintrock", line 11, in <module>
    load_entry_point('Flintrock==0.10.0.dev0', 'console_scripts', 'flintrock')()
  File "/usr/local/lib/python3.6/site-packages/flintrock/flintrock.py", line 1132, in main
    cli(obj={})
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flintrock/flintrock.py", line 523, in describe
    logger.info(cluster.name + ':', cluster.master_host)
```

* Flintrock version: master
* Python version: python3.6
* OS:

**Comment by tyg03485** [comment]
it runs with just inserting "%s".

`logger.info(cluster.name + ': %s', cluster.master_host)`
