### ISSUE TITLE
CERTIFICATE VERIFY error

### ISSUE THREAD

**Issue by rymoore** [nchammas/flintrock#286]
When trying to launch a test cluster on EC2 I'm getting:

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>`

I'm assuming I need to do something to accept a certificate for a download... can someone point me in the right direction?

**Comment by nchammas** [comment]
Are you on a corporate network that may intercept SSL traffic?

Where exactly in the launch process do you get this error? Please show the full output.

**Comment by rymoore** [comment]
I've tried on 3 different Wifi networks (all non-corporate). I'm on a Macbook Pro. Here are the exact results when I run:

```
Warning: Downloading Spark from an Apache mirror. Apache mirrors are often slow and unreliable, and typically only serve the most recent releases. We strongly recommend you specify a custom download source. For more background on this issue, please see: https://github.com/nchammas/flintrock/issues/238
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/flintrock", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flintrock/flintrock.py", line 1187, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flintrock/flintrock.py", line 410, in launch
    validate_download_source(spark_download_source)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flintrock/flintrock.py", line 208, in validate_download_source
    urllib.request.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
```

**Comment by rymoore** [comment]
Figured it out - had to follow this:

https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate

**Comment by nchammas** [comment]
Glad you found a solution, and thanks for sharing the link!

**Comment by rk186009** [comment]
I am getting the same issue when using the standalone mode on a t2.micro instance in the AWS free tier.

Following is what I used to install flintrock:

export flintrock_version="0.11.0"
cd /opt
curl --location --remote-name "https://github.com/nchammas/flintrock/releases/download/v$flintrock_version/Flintrock-$flintrock_version-standalone-Linux-x86_64.zip"
unzip -q -d flintrock "Flintrock-$flintrock_version-standalone-Linux-x86_64.zip"

Then I configured it, more or less the default way.

Then here's the command I run and the error:

[root@ip-172-31-10-232 flintrock]# ./flintrock launch spark-cluster
Warning: Downloading Spark from an Apache mirror. Apache mirrors are often slow and unreliable, and typically only serve the most recent releases. We strongly recommend you specify a custom download source. For more background on this issue, please see: https://github.com/nchammas/flintrock/issues/238
Traceback (most recent call last):
  File "urllib/request.py", line 1317, in do_open
  File "http/client.py", line 1229, in request
  File "http/client.py", line 1275, in _send_request
  File "http/client.py", line 1224, in endheaders
  File "http/client.py", line 1016, in _send_output
  File "http/client.py", line 956, in send
  File "http/client.py", line 1392, in connect
  File "ssl.py", line 412, in wrap_socket
  File "ssl.py", line 853, in _create
  File "ssl.py", line 1117, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "standalone.py", line 11, in <module>
  File "flintrock/flintrock.py", line 1187, in main
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "flintrock/flintrock.py", line 410, in launch
  File "flintrock/flintrock.py", line 208, in validate_download_source
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1360, in https_open
  File "urllib/request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
[4078] Failed to execute script standalone

I looked at the above trail of the issue and also googled around. I don't know Python. I have Python version 2.7.14. But as I am using the standalone mode, I don't think it is related. Can you please help solve this?

**Comment by nchammas** [comment]
@rk186009 - Have you tried applying the solution that @rymoore linked to?

Also, have you tried running Flintrock from a different network (e.g. home vs. office) to see if your issue is related to certificate tampering (which is common on corporate networks)?

**Comment by rk186009** [comment]
> @rk186009 - Have you tried applying the solution that @rymoore linked to?
> 
> Also, have you tried running Flintrock from a different network (e.g. home vs. office) to see if your issue is related to certificate tampering (which is common on corporate networks)?

I was able to proceed with the regular version (not the standalone one), by installing Python 3 first.

However, I am now getting stuck at a later point in the launch process. I will check and raise an issue as needed.
