### ISSUE TITLE
Flintrock got stuck when restarting a Spark cluster on AWS

### ISSUE THREAD

**Issue by foolhb** [nchammas/flintrock#293]
* Flintrock version: 0.11.0
* Python version: Python 3.6.8 :: Anaconda, Inc.
* OS: Mac

I used Flintrock to start a Spark cluster on AWS and stopped it after using it. Then I restarted the cluster using the command: flintrock start --ec2-identity-file ./AWS.pem cluster-name
But it got stuck at "Starting big-spark..." and ended up "[IP address] Could not connect via SSH." The instances were successfully stared, but the Spark seems not stared since I can't access 8080 port of the master instance

I'm not sure if this should be posted here, but I did try to Google for some information but got nothing. Thanks for your help!

**Comment by foolhb** [comment]
Update: I checked the inbound list of Flintrock security group and found that only my_local_ip/32 was allowed to SSH to the instance. I updated it and allow any of my ports SSH to the instance. 
Now it goes to:
Starting big-spark...
[52.90.16.14] SSH online.
[184.72.105.34] SSH online.
[35.171.150.116] SSH online.
[52.90.16.14] Configuring HDFS master...
[52.90.16.14] Configuring Spark master...

And then failed due to HDFS health check failed. Here is the traceback:

Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/flintrock/services.py", line 236, in health_check
    .urlopen(hdfs_master_ui)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flintrock", line 11, in <module>
    load_entry_point('Flintrock==0.11.0', 'console_scripts', 'flintrock')()
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/flintrock/flintrock.py", line 1187, in main
    cli(obj={})
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/flintrock/flintrock.py", line 669, in start
    cluster.start(user=user, identity_file=identity_file)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/flintrock/ec2.py", line 53, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/flintrock/ec2.py", line 207, in start
    identity_file=identity_file)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/flintrock/core.py", line 248, in start
    service.health_check(master_host=self.master_ip)
  File "/usr/local/Cellar/flintrock/0.11.0_3/libexec/lib/python3.7/site-packages/flintrock/services.py", line 241, in health_check
    raise Exception("HDFS health check failed.") from e
Exception: HDFS health check failed.


Thank you!

**Comment by nchammas** [comment]
Hmm, everything else was the same, and you just installed Flintrock with pip instead of Homebrew? That's strange. It should have worked with Homebrew (even though it's an unofficial installation method), but I'm glad you're all set now!
