### ISSUE TITLE
Timed out waiting for HDFS master to come up.

### ISSUE THREAD

**Issue by marcoeg** [nchammas/flintrock#325]
* Flintrock version: 1.0.0
* Python version: 3.7.1
* OS: Ubuntu 18.04

Having hard time to start a cluster:

```
(spark) marco@spirale-dev:~/Development/virtualenvs$ flintrock --debug launch spark-cluster
2021-01-14 17:38:24,910 - flintrock.ec2       - INFO  - Launching 3 instances...
2021-01-14 17:38:37,247 - flintrock.ec2       - DEBUG - 3 instances not in state 'running': 'i-081f549caae99bd78', 'i-05b78e1874c84af66', 'i-02a0b75c3d7e7c336', ...
2021-01-14 17:38:43,482 - flintrock.ssh       - DEBUG - [54.215.46.219] SSH timeout.
2021-01-14 17:38:43,483 - flintrock.ssh       - DEBUG - [54.193.189.133] SSH timeout.
2021-01-14 17:38:43,486 - flintrock.ssh       - DEBUG - [54.193.98.110] SSH timeout.
2021-01-14 17:38:48,507 - flintrock.ssh       - DEBUG - [54.193.98.110] SSH exception: [Errno None] Unable to connect to port 22 on 54.193.98.110
2021-01-14 17:38:48,542 - flintrock.ssh       - DEBUG - [54.193.189.133] SSH exception: [Errno None] Unable to connect to port 22 on 54.193.189.133
2021-01-14 17:38:48,761 - flintrock.ssh       - INFO  - [54.215.46.219] SSH online.
2021-01-14 17:38:49,141 - flintrock.core      - INFO  - [54.215.46.219] Configuring ephemeral storage...
2021-01-14 17:38:49,612 - flintrock.core      - INFO  - [54.215.46.219] Installing Java 1.8...
2021-01-14 17:38:53,822 - flintrock.ssh       - INFO  - [54.193.98.110] SSH online.
2021-01-14 17:38:53,850 - flintrock.ssh       - INFO  - [54.193.189.133] SSH online.
2021-01-14 17:38:54,154 - flintrock.core      - INFO  - [54.193.98.110] Configuring ephemeral storage...
2021-01-14 17:38:54,377 - flintrock.core      - INFO  - [54.193.189.133] Configuring ephemeral storage...
2021-01-14 17:38:54,608 - flintrock.core      - INFO  - [54.193.98.110] Installing Java 1.8...
2021-01-14 17:38:54,976 - flintrock.core      - INFO  - [54.193.189.133] Installing Java 1.8...
2021-01-14 17:39:11,668 - flintrock.services  - INFO  - [54.193.189.133] Installing HDFS...
2021-01-14 17:39:15,128 - flintrock.services  - INFO  - [54.215.46.219] Installing HDFS...
2021-01-14 17:39:16,721 - flintrock.services  - INFO  - [54.193.98.110] Installing HDFS...
2021-01-14 17:39:41,972 - flintrock.services  - INFO  - [54.193.189.133] Installing Spark...
2021-01-14 17:39:45,131 - flintrock.services  - INFO  - [54.215.46.219] Installing Spark...
2021-01-14 17:39:46,820 - flintrock.services  - INFO  - [54.193.98.110] Installing Spark...
2021-01-14 17:40:43,353 - flintrock.services  - INFO  - [54.193.98.110] Configuring HDFS master...
2021-01-14 17:42:42,805 - flintrock.services  - DEBUG - Timed out waiting for HDFS master to come up. Trying again...
2021-01-14 17:44:44,679 - flintrock.services  - DEBUG - Timed out waiting for HDFS master to come up. Trying again...
2021-01-14 17:46:46,707 - flintrock.services  - DEBUG - Timed out waiting for HDFS master to come up.
Do you want to terminate the 3 instances created by this operation? [Y/n]: Y
Terminating instances...
Traceback (most recent call last):
  File "/home/marco/Development/virtualenvs/spark/bin/flintrock", line 8, in <module>
    sys.exit(main())
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/flintrock/flintrock.py", line 1187, in main
    cli(obj={})
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/flintrock/flintrock.py", line 456, in launch
    tags=ec2_tags)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/flintrock/ec2.py", line 53, in wrapper
    res = func(*args, **kwargs)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/flintrock/ec2.py", line 955, in launch
    identity_file=identity_file)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/flintrock/core.py", line 651, in provision_cluster
    cluster=cluster)
  File "/home/marco/Development/virtualenvs/spark/lib/python3.7/site-packages/flintrock/services.py", line 226, in configure_master
    raise Exception("Time out waiting for HDFS master to come up.")
Exception: Time out waiting for HDFS master to come up.
```

I logged into the master before terminating the instances and got the included Hadoop log.

Using the following configuration:

```
services:
  spark:
    version: 2.4.7
    # git-commit: latest  # if not 'latest', provide a full commit SHA; e.g. d6dc12ef0146ae409834c78737c116050961f350
    # git-repository:  # optional; defaults to https://github.com/apache/spark
    # optional; defaults to download from from the official Spark S3 bucket
    #   - must contain a {v} template corresponding to the version
    #   - Spark must be pre-built
    #   - must be a tar.gz file
    download-source: "http://mirrors.advancedhosters.com/apache/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz"
    
  hdfs:
    version: 2.7.7
    # optional; defaults to download from a dynamically selected Apache mirror
    #   - must contain a {v} template corresponding to the version
    #   - must be a .tar.gz file
    download-source: "https://archive.apache.org/dist/hadoop/common/hadoop-2.7.7/hadoop-2.7.7.tar.gz"

provider: ec2

providers:
  ec2:
    key-name: Cometa
    identity-file: /home/marco/Cometa.pem
    instance-type: r5.large
    region: us-west-1
    # availability-zone: <name>
    ami: ami-0a1ef8665fe122a96
    user: ec2-user
    # ami: ami-61bbf104  # CentOS 7, us-west-1
    # user: centos
    # spot-price: <price>
    vpc-id: vpc-1cea0879
    subnet-id: subnet-745c6f32
    # placement-group: <name>
    # security-groups:
    #   - group-name1
    #   - group-name2
    instance-profile-name: EMR_EC2_DefaultRole
    # tags:
    #   - key1,value1
    #   - key2, value2  # leading/trailing spaces are trimmed
    #   - key3,  # value will be empty
    # min-root-ebs-size-gb: <size-gb>
    tenancy: default  # default | dedicated
    ebs-optimized: no  # yes | no
    instance-initiated-shutdown-behavior: terminate  # terminate | stop
    # user-data: /path/to/userdata/script

launch:
  num-slaves: 2
  install-hdfs: True
  install-spark: True

debug: false
```
Please advise.

[hadoop.log](https://github.com/nchammas/flintrock/files/5817916/hadoop.log)

**Comment by marcoeg** [comment]
Solved by creating a new VPC and subnet.

**Comment by nchammas** [comment]
Thanks for submitting a complete issue report. Are you all set now that you've created a new VPC and subnet? (Though I don't see how that would have solved things for you.)

If you're still having the same issue, two things I would do are:
1. Try HDFS 2.8.5. It's known to work with Spark 2.4, and I believe it's Flintrock's default.
2. You posted the HDFS secondary named node log. Check and post the primary log. There are probably some more informative messages in there.

**Comment by marcoeg** [comment]
Thank you for the quick reply and for providing such an useful tool. The problem was that I used an existing VPC with some custom settings for the domain name and DNS.
