### ISSUE TITLE
get error when running "flintrock configure" command

### ISSUE THREAD

**Issue by haowu24** [nchammas/flintrock#347]
* Flintrock version: 2.0.0
* Python version: 3.10.0
* OS: macOS Monterey

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/flintrock", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flintrock/flintrock.py", line 1247, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flintrock/flintrock.py", line 268, in cli
    config_map = config_to_click(normalize_keys(config_raw))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flintrock/flintrock.py", line 1115, in config_to_click
    {service + '_' + k: v for (k, v) in config['services'][service].items()})
AttributeError: 'str' object has no attribute 'items'
```

**Comment by nchammas** [comment]
Have you manually edited the Flintrock config file before? Can you share the full contents of your config file?

If you don't know where the default config file is, run `flintrock configure --locate`, and Flintrock will open the folder containing the file.

**Comment by haowu24** [comment]
Thanks for your reply. And I have solved this issue by reinstall the system.
